version: '3.8'
services:
  mysql-service:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=TechStoryBlog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password


  spring-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/techstoryblog
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysql-service
