version: "3"
services:
  mysql-service:
      image: techstoryblog
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=techstoryblog
        - MYSQL_USER=root
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
  spring-service:
    image: techstoryblog
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
