version: '3.8'
services:
  mysql-service:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=TechStoryBlog
      - MYSQL_USER=abcode
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password


  spring-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://techstoryblog-mysql-service-1:3306/techstoryblog
      - SPRING_DATASOURCE_USERNAME=abcode
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysql-service
